# Handling imbalanced dataset
during imbalanced dataset do not check only the accuracy, check all the metrics

datasetlink: https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud

In [1]:
 import pandas as pd

In [2]:
df=pd.read_csv('creditcard.csv')
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [3]:
# Checking null values

df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [4]:
# dependent feature output value

df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

This is very very huge difference, it leads to imbalanced dataset

In [5]:
# diving all features into independent and dependent feature

X=df.drop('Class',axis=1)
y=df.Class

# Techniques

## Under Sampling

suppose,   0-1000points, 1-100points

undersampling --- reduce the points of the maximum labels

i.e, reducing the 1000 points 

Disadvantage:
1. loss of data

use undersampling when you have very less dataset

In [10]:
#train test split

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7)

In [11]:
from collections import Counter
#from imblearn.under_sampling import NearMiss
#ns=NearMiss(0.80)  ## reducing it to 80%
#X_train_ns,y_train_ns=ns.fit_sample(X_train,y_train)

from imblearn.under_sampling import RandomUnderSampler
ns=RandomUnderSampler(0.8)  ## reducing 0 it to 80%
X_train_ns,y_train_ns=ns.fit_resample(X_train,y_train)

print('The number of classes befor fit {}'.format(Counter(y_train)))
print('The number of classes after fit {}'.format(Counter(y_train_ns)))

The number of classes befor fit Counter({0: 199027, 1: 337})
The number of classes after fit Counter({0: 421, 1: 337})


In [12]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[83398  1890]
 [   13   142]]
0.9777278419531149
              precision    recall  f1-score   support

           0       1.00      0.98      0.99     85288
           1       0.07      0.92      0.13       155

    accuracy                           0.98     85443
   macro avg       0.53      0.95      0.56     85443
weighted avg       1.00      0.98      0.99     85443



In result, precision is very very less soooo never do undersampling for large dataset

## Over Sampling

In [15]:
#train test split

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7)

In [19]:
from imblearn.over_sampling import RandomOverSampler

ns=RandomOverSampler(0.75)   ## increasing 1 it to 80%
X_train_ns,y_train_ns=ns.fit_resample(X_train,y_train)

print('The number of classes befor fit {}'.format(Counter(y_train)))
print('The number of classes after fit {}'.format(Counter(y_train_ns)))

C:\Users\BRAGADEESH\anaconda3\envs\featurengineering\lib\site-packages\imblearn\utils\_validation.py:586: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


The number of classes befor fit Counter({0: 199033, 1: 331})
The number of classes after fit Counter({0: 199033, 1: 149274})


In [20]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85272    10]
 [   34   127]]
0.9994850368081645
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85282
           1       0.93      0.79      0.85       161

    accuracy                           1.00     85443
   macro avg       0.96      0.89      0.93     85443
weighted avg       1.00      1.00      1.00     85443



## SMOTETomek
It create new points of the lowest number

In [6]:
#train test split

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7)

In [12]:
from imblearn.combine import SMOTETomek
from collections import Counter

ns=SMOTETomek(0.75)  
X_train_ns,y_train_ns=ns.fit_resample(X_train,y_train)

print('The number of classes befor fit {}'.format(Counter(y_train)))
print('The number of classes after fit {}'.format(Counter(y_train_ns)))

C:\Users\BRAGADEESH\anaconda3\envs\featurengineering\lib\site-packages\imblearn\utils\_validation.py:586: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


The number of classes befor fit Counter({0: 199027, 1: 337})
The number of classes after fit Counter({0: 198302, 1: 148545})


In [13]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85274    14]
 [   26   129]]
0.9995318516437859
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85288
           1       0.90      0.83      0.87       155

    accuracy                           1.00     85443
   macro avg       0.95      0.92      0.93     85443
weighted avg       1.00      1.00      1.00     85443



## Ensemble Techniques

In [ ]:
#train test split

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7)

In [ ]:
from imblearn.ensemble import EasyEnsembleClassifier

classifier=EasyEnsembleClassifier()
classifier.fit(X_train_ns,y_train_ns)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

Lets seee, during imbalanced dataset models with decision trees has better result than other algorithms

Logistic Regression with tuning   vs    Random Forest

In [59]:
# imbalnced dataset does not heavily impact ensemble techniques where decision trees are used

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import KFold, GridSearchCV
import numpy as np

In [66]:
#creating class

log_class=LogisticRegression()

#Hyparameter Tuning

grid={'C':10.0**np.arange(-2,3),'penalty':['l1','l2']}  #see regularisation video
cv=KFold(n_splits=5,shuffle=False, random_state=None)

In [67]:
#train test split

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7)

In [68]:
clf=GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro')
clf.fit(X_train,y_train)

C:\Users\BRAGADEESH\anaconda3\envs\featurengineering\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\BRAGADEESH\anaconda3\envs\featurengineering\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\BRAGADEESH\anaconda3\envs\featurengineering\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\BRAGADEESH\anaconda3\envs\featurenginee

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [69]:
y_pred=clf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85259    27]
 [   51   106]]
0.9990871107053826
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85286
           1       0.80      0.68      0.73       157

    accuracy                           1.00     85443
   macro avg       0.90      0.84      0.87     85443
weighted avg       1.00      1.00      1.00     85443



In [72]:


class_weight=dict({0:1,1:100})

In [73]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(class_weight=class_weight)
classifier.fit(X_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [74]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85279     7]
 [   41   116]]
0.9994382219725431
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85286
           1       0.94      0.74      0.83       157

    accuracy                           1.00     85443
   macro avg       0.97      0.87      0.91     85443
weighted avg       1.00      1.00      1.00     85443



In [71]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85278     8]
 [   39   118]]
0.9994499256814484
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85286
           1       0.94      0.75      0.83       157

    accuracy                           1.00     85443
   macro avg       0.97      0.88      0.92     85443
weighted avg       1.00      1.00      1.00     85443

